### ISSUE TITLE
ambiguous instruction "cd [path to project]/dist_local"

### ISSUE THREAD

**Issue by Iowastater** [npiccolotto/tbss-vis#3]
Instruction given as "cd [path to project]/dist_local", but there are multiple possible systems that this command could be referring to.  Tried the ones I know of, with no success.

*** Is it possible to give details on which system is being referred to? ***

I looked up the path used in the RStudio terminal
 
![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/dbb545d0-dfe4-4485-821a-8090ce4dbfe0)

In order to follow this command "cd [path to project]/dist_local", I was expecting that the file would be dated today, 9/5/23 because I just ran the api.R script successfully.
 
![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/e1af9dc1-9a9f-4f55-a022-4e0b5ef2895a)

Seems incorrect that the date on "local_host" would be 8/4/23. Makes me wonder if today's "dist_local" file was written to a location other than the path used in the RStudio terminal.
 
![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/1d62f0ab-1ec0-4e52-b634-b359cee6468f)

Assuming that the dist-local folder location has been successfully identified, try to follow the command

cd [path to project]/dist_local

This appears to be a command line, and the instructions say that Python will be used to run the HTML file. Is this command supposed to run in a new command line window? Or is it supposed to be run within Python? Or even within the terminal window back from RStudio?
![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/13f8fc53-7270-4ebb-8277-6ef84a514fc3)

![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/2cdb1606-bd70-4b9a-b2f5-26ce898d1214)
![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/056d83db-78c9-45c3-b27f-4ec9e491445d)

**Comment by npiccolotto** [comment]
Hi,

first of all I want to point out it would be preferable if you'd add another comment to the original discussion (#2) if you refer to one of my comments there. 

Regarding the other things, I'm not sure what you call a `system`. There is only one path on your computer to the TBSSvis that you use. That path is the `[path to project]`, as you noticed. The `dist_local` folder is not written when you run the TBSSvis backend — it just comes with everything else. That's why the folder's modification date is not what you expect. 

The `python` command is supposed to be run in a new terminal window. This is already close:

![image](https://github.com/npiccolotto/tbss-vis/assets/7769312/13f8fc53-7270-4ebb-8277-6ef84a514fc3)

Now, I don't know what the Python executable (the thing that starts Python 3.11 as in your last screenshot) is called on your computer or where it is. I don't use Windows. It might be just `python`, it might be `python3.11`, it might not be in your `PATH` environment at all. I leave it up to you to figure that out. Once you have that, replace `python3` in my suggestion with the (path to the) Python binary on your computer.

I'll close this thread, please reply to #2 for more comments around this topic.

Hope this helps!

**Comment by Iowastater** [comment]
Nikolaus, thank you for your reply.  I thought you had not seen my comment in the original discussion (#2<https://urldefense.com/v3/__https:/github.com/npiccolotto/tbss-vis/issues/2__;!!Nkc5UzxO!vDJj_66Pf5Ktf9TnQsbUNeEbP_4fY4DeT9RIuawjVebhOAtZ2xYtCyP7dbos2pwYMv_ZSF7pXdG1T9EhMMI7L6UZHQ$>).

I made a comment on September 5.    When I had not seen a reply for a week, I thought maybe you did not get alerted to new comments in old discussions.  So I Opened a new discussion.  I would say this was a misunderstanding, I hope you are not offended.

I will read through the technical details of your reply tomorrow, and see if I or my team can implement them.  It seems me and my team are having difficulty trying to decipher the setup of your laptop.  I am getting the impression that TBSSvis is perhaps only coded to work on laptops with your specific setup.  But we will keep trying.  But my team is has many years of experience in setting up IT applications, we will keep trying to interpret the TBSSvis with your help.

Regards, Paul
